### ISSUE TITLE
Better message in case of HTTP errors

### ISSUE THREAD

**Issue by ariebovenberg** [ariebovenberg/quiz#10]
Issue #7 has illustrated that if the GraphQL server returns a 400 HTTP status code, urllib does not give back a descriptive message.

**Comment by rmarren1** [comment]
I got some good results wrapping this line: https://github.com/ariebovenberg/quiz/blob/90c1c4e2e95dbc3c57844a9a45ba6c2dd08d8d73/quiz/execution.py#L77
with
```
try:
    return snug.execute(snug_query, **kwargs) 
except urllib.error.HTTPError as http_error:
    error_json = json.loads(str(http_error.fp.read()))
    for err in error_json['errors']:
        print(err['stack'])
    raise Exception('Bad GraphQL request!')
```

**Comment by ariebovenberg** [comment]
Looking at your error handling code @rmarren1, it seems best to allow users to specify their own error handling. Each GraphQL server will likely use HTTP status codes in a different way, requiring different parsing behavior. `quiz` should support this. I've created issue #13 for this.

For now: the most general behavior, which should work with most servers, is to raise something like `HTTPStatus` exception, with the response text included.

I'm closing this issue for now, as `snug` release 1.3.3 fixes this issue. See #13 for further discussion on middleware.

**Comment by ariebovenberg** [comment]
reopening for now: we still need to properly handle http error status codes in the default case.

**Comment by ariebovenberg** [comment]
Fixed in `develop` branch, to be part in the next release, `0.1.0`

**Comment by ariebovenberg** [comment]
version 0.1.0 has been released. closed.
