### ISSUE TITLE
Does it support headers?

### ISSUE THREAD

**Issue by dhruvdcoder** [ariebovenberg/quiz#4]
I was trying to execute the example in the readme with Bearer Authorization header instead of auth. I passed it as keyword argument : `headers={'Authorization': 'Bearer token'}` but it gave the following error:

```
return snug.execute(as_http(as_gql(obj), url), **kwargs)
TypeError: execute() got an unexpected keyword argument 'headers'
```

**Comment by dhruvdcoder** [comment]
Never mind, found the solution in [snug's docs](https://snug.readthedocs.io/en/latest/advanced.html#authentication-methods)

**Comment by ariebovenberg** [comment]
As of release 0.0.3, custom authentication is described [in the docs](https://quiz.readthedocs.io/en/latest/advanced.html)
