### ISSUE TITLE
schema.get()  gives KeyError 'types'

### ISSUE THREAD

**Issue by dhruvdcoder** [ariebovenberg/quiz#5]
You might want to add `result['__schema']` instead of `result` [ here ](https://github.com/ariebovenberg/quiz/blob/4475c48e7fcedf153f0bbb37995f31ddc92210a5/quiz/schema/to_types.py#L180) as the result is in the following form:

```
{
  "data": {
    "__schema": {
      "queryType": {
        "name": "Query"
      },
      "mutationType": {
        "name": "Mutation"
      },
      "subscriptionType": null,
      "types": [
        {
          "kind": "SCALAR",
          "name": "Boolean",
          "description": "Represents `true` or `false` values.",
. . .
. . .

````

The corresponding test passes because in the [example schema](https://github.com/ariebovenberg/quiz/blob/4475c48e7fcedf153f0bbb37995f31ddc92210a5/tests/schema/example_schema.json#L1) for the test, the json starts from `__schema` and not `data`

**Comment by ariebovenberg** [comment]
@dhruvdcoder thanks for the feedback! I'll definitely fix this in the next release.

**Comment by ariebovenberg** [comment]
Fixed in `develop` branch. Expecting to release it this week.

**Comment by ariebovenberg** [comment]
version `0.0.3` has been released, which fixes this. closed.
