### ISSUE TITLE
More verbose 404?

### ISSUE THREAD

**Issue by orwell1984** [ariebovenberg/quiz#82]
Hi! Great library, thanks for making it.
I have one small suggestion - add verbose flag to the http errors.
I'm currently seeing ```quiz.execution.HTTPError: Response with status 404, content: b'{"message":"The requested URL \\"/foobar\\" was not found on this server."}'```. I'd rather see ```https://example.com/foobar?query={blah...``` so I don't have to make sure of how the URL got glued together etc by other means that simply running Python.

Would what be Quiz-related or is all http activity bing handled by Snug?

**Comment by ariebovenberg** [comment]
Hi @orwell1984, thanks for opening this issue!

background: `snug` handles making requests, but only raises errors when the request itself cannot be made (e.g. connection problems). Errors following from response status codes are raised by `quiz`.

On to your issue.

`HTTPError` does include the full response in the `.response` attribute. However, it does not include the _request_ context. I've created release 0.1.3 to address this (#83).

When 0.1.3 is released, you can do this:

```python

try:
    result = quiz.execute(...)
except quiz.HTTPError as e:
    # request includes url, params, headers, etc.
    print('full request information: {}'.format(e.request))
```

The exception message is also more clear, for example:

```
Response with status 404, content: b'not found!\x00' for URL "https://my.url/api". View this exception's `request` and `response` attributes for detailed info.
```

**Comment by ariebovenberg** [comment]
version 0.1.3 has been released, including the fix in the comment above. closed.

**Comment by orwell1984** [comment]
Wow, that was quick! Thanks a lot @ariebovenberg !
